# Generated by Django 4.2.13 on 2024-07-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=300)),
                ('city_name', models.CharField(max_length=300)),
                ('postal_zone', models.CharField(max_length=128)),
                ('country_subentity', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
            ],
        ),
    ]
