# Generated by Django 4.2.13 on 2024-07-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0002_postaladdress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=300)),
                ('party_contact_email', models.CharField(max_length=300)),
                ('party_legal_entity_name', models.CharField(max_length=300)),
                ('party_legal_entity_id', models.CharField(max_length=300)),
                ('party_postal_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xrechnung_light.postaladdress')),
            ],
        ),
    ]
