# Generated by Django 4.2.13 on 2024-07-25 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xrechnung_light', '0003_customerparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='logmessage',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='logmessage',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='logmessage',
            name='deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='logmessage',
            name='owned_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
