# Generated by Django 4.2.13 on 2024-07-30 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xrechnung_light', '0005_alter_logmessage_generic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaladdress',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('0f77c10c-ddcc-482c-97d0-8e6f7cca3c0c')),
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='owned_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('0f77c10c-ddcc-482c-97d0-8e6f7cca3c0c')),
        ),
    ]
