# Generated by Django 4.2.13 on 2024-07-30 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0006_postaladdress_active_postaladdress_changed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('97fdaeac-177e-4154-af12-2a5eb805471f')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='country_subentity',
            field=models.CharField(choices=[('Rlp', 'Rheinland-Pfalz'), ('He', 'Hessen')], default='Rlp', max_length=128),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('97fdaeac-177e-4154-af12-2a5eb805471f')),
        ),
    ]
