# Generated by Django 4.2.13 on 2024-07-30 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xrechnung_light', '0008_alter_logmessage_created_alter_logmessage_generic_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerparty',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerparty',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customerparty',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customerparty',
            name='deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('6c68c678-df4b-470e-8750-2597b611aefb')),
        ),
        migrations.AddField(
            model_name='customerparty',
            name='owned_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('6c68c678-df4b-470e-8750-2597b611aefb')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('6c68c678-df4b-470e-8750-2597b611aefb')),
        ),
    ]
