# Generated by Django 4.2.13 on 2024-07-30 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xrechnung_light', '0009_customerparty_active_customerparty_changed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.UUID('1b1bef4b-9e64-4e04-a69b-03e0eebaa2eb'))),
                ('created', models.DateTimeField(null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('identifier', models.CharField(max_length=300)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('actual_delivery_date', models.DateField()),
                ('buyer_reference', models.CharField(max_length=1024)),
                ('order_reference', models.CharField(max_length=1024)),
                ('project_reference_id', models.CharField(max_length=1024)),
                ('payment_terms', models.CharField(max_length=4096)),
                ('prepaid_amount', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('1b1bef4b-9e64-4e04-a69b-03e0eebaa2eb')),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('1b1bef4b-9e64-4e04-a69b-03e0eebaa2eb')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('1b1bef4b-9e64-4e04-a69b-03e0eebaa2eb')),
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.UUID('1b1bef4b-9e64-4e04-a69b-03e0eebaa2eb'))),
                ('created', models.DateTimeField(null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=16)),
                ('unit', models.CharField(max_length=300)),
                ('number_of_units', models.IntegerField()),
                ('tax', models.DecimalField(decimal_places=2, max_digits=16)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xrechnung_light.invoice')),
                ('owned_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xrechnung_light.customerparty'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='owned_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
