# Generated by Django 4.2.13 on 2024-07-31 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0010_invoice_alter_customerparty_generic_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceline',
            old_name='category',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='description',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='title',
        ),
        migrations.AlterField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('ae070717-bdd4-444b-b8f1-82ec71821677')),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('ae070717-bdd4-444b-b8f1-82ec71821677')),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='identifier',
            field=models.CharField(help_text="Beispiel: '34-321321'", max_length=300, verbose_name='Rechnungsidentifikator'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(help_text="Beispiel: '2024-07-30'", verbose_name='Rechnungsdatum'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('ae070717-bdd4-444b-b8f1-82ec71821677')),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('ae070717-bdd4-444b-b8f1-82ec71821677')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('ae070717-bdd4-444b-b8f1-82ec71821677')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='street_name',
            field=models.CharField(help_text="Beispiel: 'Musterstraße 10'", max_length=300, verbose_name='Strasse und Hausnummer'),
        ),
    ]
