# Generated by Django 4.2.13 on 2024-07-31 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0011_rename_category_invoiceline_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='farbe',
            field=models.CharField(default='te', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('a9fd42a2-dcd2-4704-a59a-122bc028d1f4')),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('a9fd42a2-dcd2-4704-a59a-122bc028d1f4')),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('a9fd42a2-dcd2-4704-a59a-122bc028d1f4')),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('a9fd42a2-dcd2-4704-a59a-122bc028d1f4')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('a9fd42a2-dcd2-4704-a59a-122bc028d1f4')),
        ),
    ]
