# Generated by Django 4.2.13 on 2024-08-01 05:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0012_invoice_farbe_alter_customerparty_generic_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='farbe',
        ),
        migrations.AlterField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('31e7de92-d1dd-43eb-83f9-3a49eb2db2e5')),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('31e7de92-d1dd-43eb-83f9-3a49eb2db2e5')),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('31e7de92-d1dd-43eb-83f9-3a49eb2db2e5')),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('31e7de92-d1dd-43eb-83f9-3a49eb2db2e5')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('31e7de92-d1dd-43eb-83f9-3a49eb2db2e5')),
        ),
    ]
