# Generated by Django 4.2.13 on 2024-08-01 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xrechnung_light', '0013_remove_invoice_farbe_alter_customerparty_generic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('8b9aef65-f6e3-4c79-ad59-b4c6a30654f5')),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('8b9aef65-f6e3-4c79-ad59-b4c6a30654f5')),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('8b9aef65-f6e3-4c79-ad59-b4c6a30654f5')),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('8b9aef65-f6e3-4c79-ad59-b4c6a30654f5')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('8b9aef65-f6e3-4c79-ad59-b4c6a30654f5')),
        ),
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.UUID('8b9aef65-f6e3-4c79-ad59-b4c6a30654f5'))),
                ('created', models.DateTimeField(null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('identifier', models.CharField(max_length=1024)),
                ('filename', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=4096)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xrechnung_light.invoice')),
                ('owned_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
