# Generated by Django 4.2.13 on 2024-08-01 19:00

from django.db import migrations, models
import xrechnung_light.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0014_alter_customerparty_generic_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceattachment',
            name='filename',
        ),
        migrations.AlterField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('bdefd555-fbcd-4b73-8539-b6ab54c5b5f6')),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('bdefd555-fbcd-4b73-8539-b6ab54c5b5f6')),
        ),
        migrations.AlterField(
            model_name='invoiceattachment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=xrechnung_light.models.InvoiceAttachment.get_upload_path),
        ),
        migrations.AlterField(
            model_name='invoiceattachment',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('bdefd555-fbcd-4b73-8539-b6ab54c5b5f6')),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('bdefd555-fbcd-4b73-8539-b6ab54c5b5f6')),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('bdefd555-fbcd-4b73-8539-b6ab54c5b5f6')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('bdefd555-fbcd-4b73-8539-b6ab54c5b5f6')),
        ),
    ]
