# Generated by Django 4.2.13 on 2024-08-01 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0015_remove_invoiceattachment_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='identifier',
            field=models.CharField(default='testid', help_text="Beispiel: '1.1.1'", max_length=300, verbose_name='Identifikator'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('4be9f2d6-75ce-45ff-a085-f2c05356884c')),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('4be9f2d6-75ce-45ff-a085-f2c05356884c')),
        ),
        migrations.AlterField(
            model_name='invoiceattachment',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('4be9f2d6-75ce-45ff-a085-f2c05356884c')),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('4be9f2d6-75ce-45ff-a085-f2c05356884c')),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('4be9f2d6-75ce-45ff-a085-f2c05356884c')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('4be9f2d6-75ce-45ff-a085-f2c05356884c')),
        ),
    ]
