# Generated by Django 4.2.13 on 2024-08-02 07:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0016_invoiceline_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('f5d9b785-f0a0-41da-861d-b5f735d4ac50')),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('f5d9b785-f0a0-41da-861d-b5f735d4ac50')),
        ),
        migrations.AlterField(
            model_name='invoiceattachment',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('f5d9b785-f0a0-41da-861d-b5f735d4ac50')),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('f5d9b785-f0a0-41da-861d-b5f735d4ac50')),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='unit',
            field=models.CharField(choices=[('H87', 'Stück'), ('C62', 'ein'), ('MTK', 'Quadratmeter'), ('LM', 'Laufende Meter')], max_length=5),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('f5d9b785-f0a0-41da-861d-b5f735d4ac50')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('f5d9b785-f0a0-41da-861d-b5f735d4ac50')),
        ),
    ]
