# Generated by Django 4.2.13 on 2024-08-02 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import xrechnung_light.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xrechnung_light', '0017_alter_customerparty_generic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('f246ef65-acb7-496f-8bca-b890a5deeb98')),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('f246ef65-acb7-496f-8bca-b890a5deeb98')),
        ),
        migrations.AlterField(
            model_name='invoiceattachment',
            name='attachment',
            field=models.FileField(blank=True, help_text='https://docs.peppol.eu/poacc/billing/3.0/codelist/MimeCode/', null=True, upload_to=xrechnung_light.models.InvoiceAttachment.get_upload_path, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='invoiceattachment',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('f246ef65-acb7-496f-8bca-b890a5deeb98')),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('f246ef65-acb7-496f-8bca-b890a5deeb98')),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('f246ef65-acb7-496f-8bca-b890a5deeb98')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('f246ef65-acb7-496f-8bca-b890a5deeb98')),
        ),
        migrations.CreateModel(
            name='MyParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_id', models.UUIDField(default=uuid.UUID('f246ef65-acb7-496f-8bca-b890a5deeb98'))),
                ('created', models.DateTimeField(null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('party_name', models.CharField(max_length=300)),
                ('party_contact_email', models.CharField(max_length=300)),
                ('party_legal_entity_name', models.CharField(max_length=300)),
                ('party_legal_entity_id', models.CharField(max_length=300)),
                ('party_contact_person_name', models.CharField(max_length=300)),
                ('party_contact_person_phone', models.CharField(max_length=300)),
                ('party_contact_person_email', models.CharField(max_length=300)),
                ('party_payment_financial_account_id', models.CharField(max_length=300)),
                ('party_payment_financial_account_name', models.CharField(max_length=300)),
                ('party_payment_financial_institution_id', models.CharField(max_length=300)),
                ('owned_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('party_postal_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xrechnung_light.postaladdress')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
