# Generated by Django 4.2.13 on 2024-08-02 10:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0018_alter_customerparty_generic_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='my_party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xrechnung_light.myparty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('e390343c-48b8-41da-b068-ab4c0c24b9d6')),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('e390343c-48b8-41da-b068-ab4c0c24b9d6')),
        ),
        migrations.AlterField(
            model_name='invoiceattachment',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('e390343c-48b8-41da-b068-ab4c0c24b9d6')),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('e390343c-48b8-41da-b068-ab4c0c24b9d6')),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('e390343c-48b8-41da-b068-ab4c0c24b9d6')),
        ),
        migrations.AlterField(
            model_name='myparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('e390343c-48b8-41da-b068-ab4c0c24b9d6')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('e390343c-48b8-41da-b068-ab4c0c24b9d6')),
        ),
    ]
