# Generated by Django 4.2.13 on 2024-08-02 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0019_invoice_my_party_alter_customerparty_generic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('ea313ab7-95b0-4d86-ad32-d657d426122b')),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('ea313ab7-95b0-4d86-ad32-d657d426122b')),
        ),
        migrations.AlterField(
            model_name='invoiceattachment',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('ea313ab7-95b0-4d86-ad32-d657d426122b')),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('ea313ab7-95b0-4d86-ad32-d657d426122b')),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('ea313ab7-95b0-4d86-ad32-d657d426122b')),
        ),
        migrations.AlterField(
            model_name='myparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('ea313ab7-95b0-4d86-ad32-d657d426122b')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('ea313ab7-95b0-4d86-ad32-d657d426122b')),
        ),
    ]
