# Generated by Django 4.2.13 on 2024-08-02 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0021_myparty_party_tax_id_alter_customerparty_generic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('a0b3d722-5429-4093-934f-f2a46036129a')),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('a0b3d722-5429-4093-934f-f2a46036129a')),
        ),
        migrations.AlterField(
            model_name='invoiceattachment',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('a0b3d722-5429-4093-934f-f2a46036129a')),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('a0b3d722-5429-4093-934f-f2a46036129a')),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('a0b3d722-5429-4093-934f-f2a46036129a')),
        ),
        migrations.AlterField(
            model_name='myparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('a0b3d722-5429-4093-934f-f2a46036129a')),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.UUID('a0b3d722-5429-4093-934f-f2a46036129a')),
        ),
    ]
