# Generated by Django 4.2.13 on 2024-08-06 19:34

from django.db import migrations, models
import xrechnung_light.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0023_alter_customerparty_generic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='generic_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='invoiceattachment',
            name='generic_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='generic_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='number_of_units',
            field=models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Menge'),
        ),
        migrations.AlterField(
            model_name='invoicexml',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=xrechnung_light.models.InvoiceXml.get_upload_path, verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='invoicexml',
            name='generic_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='generic_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='myparty',
            name='generic_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='generic_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
