# Generated by Django 4.2.13 on 2024-08-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0024_alter_customerparty_generic_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='unit2',
            field=models.CharField(choices=[('H87', 'Stück'), ('C62', 'ein'), ('MTK', 'Quadratmeter'), ('LM', 'Laufende Meter')], default='12345', max_length=5, verbose_name='Einheit'),
            preserve_default=False,
        ),
    ]
