# Generated by Django 4.2.13 on 2024-08-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0025_invoiceline_unit2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='unit2',
        ),
    ]
