# Generated by Django 4.2.13 on 2024-08-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0026_remove_invoiceline_unit2'),
    ]

    operations = [
        migrations.AddField(
            model_name='myparty',
            name='party_logo',
            field=models.ImageField(blank=True, help_text='Graphik mit Logo', null=True, upload_to='logos/', verbose_name='Logo'),
        ),
    ]
