# Generated by Django 4.2.13 on 2024-08-23 06:29

from django.db import migrations, models
import xrechnung_light.models


class Migration(migrations.Migration):

    dependencies = [
        ('xrechnung_light', '0027_myparty_party_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myparty',
            name='party_logo',
            field=models.ImageField(blank=True, help_text='Graphik mit Logo', null=True, upload_to=xrechnung_light.models.MyParty.get_upload_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='postal_zone',
            field=models.CharField(help_text="Beispiel: '12345'", max_length=5, verbose_name='Postleitzahl'),
        ),
    ]
